/*--------------------------------------------------------------------------------------------
Command to run model:
--dbt run --select ETL_MART_PROCUREMENT_PO_DISTRIBUTION_DIM
--dbt build --full-refresh --select +ETL_MART_PROCUREMENT_PO_DISTRIBUTION_DIM
--dbt build --select ETL_MART_PROCUREMENT_PO_DISTRIBUTION_DIM --vars 'is_backfill: True'

Version     Date            Author                Description
-------     ----------      ----------------      ----------------------------------
1.0         03/05/2026      Cortex Code           Initial Version - Auto-Generated from STTM

----------------------------------------------------------------------------------------------*/

{################# EDW Job Template Variables #################}
{%-set v_pk_list = ['PO_DISTRIBUTION_KEY']-%}
{% if is_incremental() %}
{%-set v_house_keeping_column = ['BIW_INS_DTTM','BIW_UPD_DTTM','BIW_BATCH_ID','BIW_MD5_KEY']-%}
{%-set v_all_column_list =  edw_get_column_list( this ) -%}
{%-set v_update_column_list =  edw_get_quoted_column_list( this ,v_pk_list|list + ['BIW_INS_DTTM']|list) -%}
{% endif %}

{################# Batch control insert and update SQL #################}
{%- set v_dbt_job_name = 'DBT_ETL_MART_PROCUREMENT_PO_DISTRIBUTION_DIM'-%}
-- Step 1 Batch process info
{%- set v_watermark = edw_batch_control(v_dbt_job_name,config.get('schema'),config.get('alias'),config.get('tags'),config.get('materialized') ) -%}
{%- set V_LWM = v_watermark[0] -%}
{%- set V_HWM = v_watermark[1] -%}
{%- set V_START_DTTM = v_watermark[2] -%}
{%- set V_BIW_BATCH_ID = v_watermark[3] -%}
{%- set v_sql_upd_success_batch = "CALL UTILITY.EDW_BATCH_SUCCESS_PROC('"~v_dbt_job_name~"')" -%}

{################# Snowflake Object Configuration #################}
{{
    config(
        description = 'Building ETL MART table for PO_DISTRIBUTION_DIM',
        transient=true,
        materialized='table',
        schema ='ETL_MART_PROCUREMENT',
        alias='PO_DISTRIBUTION_DIM',
        tags =['PO'],
        unique_key= v_pk_list,
        post_hook= [v_sql_upd_success_batch]  
    )
}}


WITH PO_DISTRIBUTIONS_ALL AS(
SELECT 
    PO_DISTRIBUTION_ID,
    DISTRIBUTION_NUM,
    PO_HEADER_ID,
    PO_LINE_ID,
    LINE_LOCATION_ID,
    REQ_DISTRIBUTION_ID,
    WIP_ENTITY_ID,
    BUDGET_DATE,
    CANCEL_BUDGET_DATE,
    CLOSE_BUDGET_DATE,
    CREATION_DATE,
    LAST_UPDATE_DATE,
    RATE_DATE,
    SET_OF_BOOKS_ID,
    DELIVER_TO_LOCATION_ID,
    CODE_COMBINATION_ID,
    DELIVER_TO_PERSON_ID,
    REQ_HEADER_REFERENCE_NUM,
    REQ_LINE_REFERENCE_NUM,
    PRC_BU_ID,
    REQ_BU_ID,
    WIP_LINE_ID,
    DESTINATION_ORGANIZATION_ID,
    SOLDTO_BU_ID,
    DESTINATION_TYPE_CODE,
    RATE,
    DESTINATION_SUBINVENTORY,
    DESTINATION_CONTEXT,
    DISTRIBUTION_TYPE,
    INVOICE_ADJUSTMENT_FLAG,
    ACCRUED_FLAG,
    ENCUMBERED_FLAG,
    ACCRUE_ON_RECEIPT_FLAG,
    PJC_PROJECT_ID,
    PJC_TASK_ID,
    WIP_OPERATION_SEQ_NUM,
    WIP_REPETITIVE_SCHEDULE_ID,
    WIP_RESOURCE_SEQ_NUM,
    PREVENT_ENCUMBRANCE_FLAG
FROM  {{ref('ODS_ORACLE_CLOUD_PO_DISTRIBUTIONS_ALL')}} 
WHERE 
  IS_DELETE = 'N'
AND {% if var('is_backfill') %}
        BIW_UPD_DTTM >= '{{var('refresh_start_ts')}}'
    AND BIW_UPD_DTTM < '{{V_START_DTTM}}'
    {% else %}
        BIW_UPD_DTTM >= '{{V_LWM}}' 
    AND BIW_UPD_DTTM <= '{{V_HWM}}'
    {% endif %}      
)
,PJF_PROJ_ELEMENTS_TL AS(
SELECT    
    NAME,
    LANGUAGE,
    PROJ_ELEMENT_ID
FROM {{ref('ODS_ORACLE_CLOUD_PJF_PROJ_ELEMENTS_TL')}}  
),
PJF_PROJECTS_ALL_TL AS(
SELECT 
    NAME,
    LANGUAGE,
    PROJECT_ID
FROM {{ref('ODS_ORACLE_CLOUD_PJF_PROJECTS_ALL_TL')}}
)
,
 PJF_PROJECTS_ALL_B AS
(
SELECT 
   PJF_PROJECTS_ALL_B.PROJECT_ID,
   PJF_PROJECTS_ALL_B.SEGMENT1 AS PROJECT_NUMBER,
   PJF_PROJECTS_ALL_TL.NAME     AS PROJECT_NAME
FROM {{ref('ODS_ORACLE_CLOUD_PJF_PROJECTS_ALL_B')}} PJF_PROJECTS_ALL_B
JOIN PJF_PROJECTS_ALL_TL 
ON PJF_PROJECTS_ALL_B.PROJECT_ID = PJF_PROJECTS_ALL_TL.PROJECT_ID
WHERE PJF_PROJECTS_ALL_TL.LANGUAGE = 'US'
AND PROJECT_NUMBER IS NOT NULL
)


,PJF_PROJ_ELEMENTS_B AS
(
SELECT
   PJF_PROJ_ELEMENTS_B.PROJECT_ID,
   PJF_PROJ_ELEMENTS_B.ELEMENT_NUMBER AS TASK_NUMBER, 
   PJF_PROJ_ELEMENTS_TL.NAME       AS TASK_NAME,
   PJF_PROJ_ELEMENTS_B.PROJ_ELEMENT_ID
FROM {{ref('ODS_ORACLE_CLOUD_PJF_PROJ_ELEMENTS_B')}} PJF_PROJ_ELEMENTS_B
JOIN PJF_PROJ_ELEMENTS_TL  
ON PJF_PROJ_ELEMENTS_B.PROJ_ELEMENT_ID = PJF_PROJ_ELEMENTS_TL.PROJ_ELEMENT_ID
AND PJF_PROJ_ELEMENTS_TL.LANGUAGE = 'US' 
)




SELECT 
    MD5(OBJECT_CONSTRUCT (
    'COL1',PDA.PO_DISTRIBUTION_ID::STRING
    )::STRING
    )::STRING AS PO_DISTRIBUTION_KEY,
    PDA.PO_DISTRIBUTION_ID,
    PDA.DISTRIBUTION_NUM,
    PDA.PO_HEADER_ID,
    PDA.PO_LINE_ID,
    PDA.LINE_LOCATION_ID,
    PDA.REQ_DISTRIBUTION_ID,
    PDA.WIP_ENTITY_ID,
    PDA.BUDGET_DATE,
    PDA.CANCEL_BUDGET_DATE,
    PDA.CLOSE_BUDGET_DATE,
    PDA.CREATION_DATE,
    PDA.LAST_UPDATE_DATE,
    PDA.RATE_DATE,
    PDA.SET_OF_BOOKS_ID,
    PDA.DELIVER_TO_LOCATION_ID,
    PDA.CODE_COMBINATION_ID,
    PDA.DELIVER_TO_PERSON_ID,
    PDA.REQ_HEADER_REFERENCE_NUM,
    PDA.REQ_LINE_REFERENCE_NUM,
    PDA.PRC_BU_ID,
    PDA.REQ_BU_ID,
    PDA.WIP_LINE_ID,
    PDA.DESTINATION_ORGANIZATION_ID,
    PDA.SOLDTO_BU_ID,
    PDA.DESTINATION_TYPE_CODE,
    PDA.RATE,
    PDA.DESTINATION_SUBINVENTORY,
    PDA.DESTINATION_CONTEXT,
    PDA.DISTRIBUTION_TYPE,
    PDA.INVOICE_ADJUSTMENT_FLAG,
    PDA.ACCRUED_FLAG,
    PDA.ENCUMBERED_FLAG,
    PDA.ACCRUE_ON_RECEIPT_FLAG,
    PDA.PJC_PROJECT_ID,
    PDA.PJC_TASK_ID,
    PJF_PROJECTS_ALL_B.PROJECT_NUMBER,
    PJF_PROJECTS_ALL_B.PROJECT_NAME,
    PJF_PROJ_ELEMENTS_B.TASK_NUMBER,
    PJF_PROJ_ELEMENTS_B.TASK_NAME,
    PDA.WIP_OPERATION_SEQ_NUM,
    PDA.WIP_REPETITIVE_SCHEDULE_ID,
    PDA.WIP_RESOURCE_SEQ_NUM,
    PDA.PREVENT_ENCUMBRANCE_FLAG,
    'N'::BOOLEAN as IS_DELETE,
  '{{V_START_DTTM}}'::TIMESTAMP_NTZ AS BIW_INS_DTTM,
    '{{V_START_DTTM}}'::TIMESTAMP_NTZ AS BIW_UPD_DTTM,
    '{{V_BIW_BATCH_ID}}'::NUMBER(38,0) AS BIW_BATCH_ID,
    MD5(OBJECT_CONSTRUCT (
  'COL1',PDA.PO_DISTRIBUTION_ID::STRING,
    'COL2',PDA.DISTRIBUTION_NUM::STRING,
    'COL3',PDA.PO_HEADER_ID::STRING,
    'COL4',PDA.PO_LINE_ID::STRING,
    'COL5',PDA.LINE_LOCATION_ID::STRING,
    'COL6',PDA.REQ_DISTRIBUTION_ID::STRING,
    'COL7',PDA.WIP_ENTITY_ID::STRING,
    'COL8',PDA.BUDGET_DATE::STRING,
    'COL9',PDA.CANCEL_BUDGET_DATE::STRING,
    'COL10',PDA.CLOSE_BUDGET_DATE::STRING,
    'COL11',PDA.CREATION_DATE::STRING,
    'COL12',PDA.LAST_UPDATE_DATE::STRING,
    'COL13',PDA.RATE_DATE::STRING,
    'COL14',PDA.SET_OF_BOOKS_ID::STRING,
    'COL15',PDA.DELIVER_TO_LOCATION_ID::STRING,
    'COL16',PDA.CODE_COMBINATION_ID::STRING,
    'COL17',PDA.DELIVER_TO_PERSON_ID::STRING,
    'COL18',PDA.REQ_HEADER_REFERENCE_NUM::STRING,
    'COL19',PDA.REQ_LINE_REFERENCE_NUM::STRING,
    'COL20',PDA.PRC_BU_ID::STRING,
    'COL21',PDA.REQ_BU_ID::STRING,
    'COL22',PDA.WIP_LINE_ID::STRING,
    'COL23',PDA.DESTINATION_ORGANIZATION_ID::STRING,
    'COL24',PDA.SOLDTO_BU_ID::STRING,
    'COL25',PDA.DESTINATION_TYPE_CODE::STRING,
    'COL26',PDA.RATE::STRING,
    'COL27',PDA.DESTINATION_SUBINVENTORY::STRING,
    'COL28',PDA.DESTINATION_CONTEXT::STRING,
    'COL29',PDA.DISTRIBUTION_TYPE::STRING,
    'COL30',PDA.INVOICE_ADJUSTMENT_FLAG::STRING,
    'COL31',PDA.ACCRUED_FLAG::STRING,
    'COL32',PDA.ENCUMBERED_FLAG::STRING,
    'COL33',PDA.ACCRUE_ON_RECEIPT_FLAG::STRING,
    'COL34',PDA.PJC_PROJECT_ID::STRING,
    'COL35',PDA.PJC_TASK_ID::STRING,
    'COL36',PJF_PROJECTS_ALL_B.PROJECT_NUMBER::STRING,
    'COL37',PJF_PROJECTS_ALL_B.PROJECT_NAME::STRING,
    'COL38',PJF_PROJ_ELEMENTS_B.TASK_NUMBER::STRING,
    'COL39',PJF_PROJ_ELEMENTS_B.TASK_NAME::STRING,
    'COL40',PDA.WIP_OPERATION_SEQ_NUM::STRING,
    'COL41',PDA.WIP_REPETITIVE_SCHEDULE_ID::STRING,
    'COL42',PDA.WIP_RESOURCE_SEQ_NUM::STRING,
    'COL43',PDA.PREVENT_ENCUMBRANCE_FLAG::STRING,
  'COL44',IS_DELETE::STRING
  )::STRING )::BINARY as BIW_MD5_KEY
FROM PO_DISTRIBUTIONS_ALL PDA
LEFT OUTER JOIN PJF_PROJECTS_ALL_B
ON PDA.PJC_PROJECT_ID = PJF_PROJECTS_ALL_B.PROJECT_ID
LEFT OUTER JOIN PJF_PROJ_ELEMENTS_B
ON PDA.PJC_PROJECT_ID = PJF_PROJ_ELEMENTS_B.PROJECT_ID
AND PDA.PJC_TASK_ID=PJF_PROJ_ELEMENTS_B.PROJ_ELEMENT_ID
